### ISSUE TITLE
Can't install locally because of missing PGP key

### ISSUE THREAD

**Issue by mvitz** [mauricioaniche/springlint#2]
After cloning this repo I tried to `mvn clean install` it. Unfortunatelly this fails because it tries to sign the artifact. I would suggest that only the builds that are deployed into a remote repository with `mvn deploy` should be signed.

**Comment by mauricioaniche** [comment]
I'm not an expert in Maven. If I remove both `maven-release-plugin` and leave it only in the `release-sign-artifacts` profile, that should work, right?

**Comment by mvitz** [comment]
I'm not sure right now. I will investigate later and create a PR afterwards.
